### ISSUE TITLE
Revision history : Implementation?

### ISSUE THREAD

**Issue by Shadowys** [Shadowys/hako#11]
As seen from the discussion here: https://github.com/Ranobe-Honyaku/Website/issues/8

Extending the model history method, we could store user actions within another collection within the mongodb, detailing who did what at when and where. This could be inserted just before every request to document the [input request](https://nodejs.org/api/http.html#http_message_url) and the request body.

**Comment by cloudiirain** [comment]
Would work, I think.

Is there a model history method already?

**Comment by Shadowys** [comment]
Not yet. I'm planning to implement user authorization before that so the program can capture the current active user (At least, theoretically).

**Comment by cloudiirain** [comment]
To clarify, are you thinking of maybe making a model_history collection (for all the models that we're tracking) and a user_actions collection?

**Comment by Shadowys** [comment]
Like just a user_actions collection, that would capture the following data:
{
  user_id: String,
  method: String, //GET/POST/DELETE etc
  url: String, // Like /api/v0.2/project
  hash: String  // in sha256
  object: String // the full json screenshot of the object as a string, to be referenced later with JSON.parse
}

Currently all objects does parent referencing, meaning that they contains references to their parents, but not to their children, not the full nested children. This would keep the data reasonably small for us to keep them.

**Comment by cloudiirain** [comment]
I'm just trying to imagine what it would take to build a [revision history](https://www.baka-tsuki.org/project/index.php?title=Baka_to_Test_to_Shoukanjuu&action=history).

Do you have everything you need to construct this given a project id (or a chapter id or something?)

I can see it working very well for generating [recent history](https://www.baka-tsuki.org/project/index.php?title=Special:RecentChanges), but I think you might be missing some fields to accomplish the former.

**Comment by Shadowys** [comment]
LOL I forgot to include the timestamp. I think it could be revised as follows:
```js
{
  user_id: String,
  method: String, //GET/POST/DELETE etc
  url: String, // Like /api/v0.2/project
  hash: String  // in sha256
  object: Object,
  timestap
}
```
So the object actually contains valid JSON. This way, if we wanted to generate a recent history for say a project with ID 1, we could use the following code in mongoose:
```js
models.find({"object.project_id: 1"}).sort('date', -1));
```

**Comment by cloudiirain** [comment]
Can you index on the `object.project_id` field though?

Without an index, it ends up being a linear search on what will end up being a huge collection (since every action on the app will end up in this collection). The performance will really suffer without that index.

Anything that we do models.find() for, we really need an index on it.

**Comment by Shadowys** [comment]
[Apparently not.](http://stackoverflow.com/questions/25914973/mongoose-unique-index-on-subdocument)

It might be better to just store this data outside, like 
```js
_id: String //We can parse what's happening through the method and url to reconstruct it
```

**Comment by Shadowys** [comment]
One question that arises from storing snapshots of the object is the inherent memory usage. 

I would suggest that for strings, we keep a diff history instead, using the [jsdiff tool](https://github.com/kpdecker/jsdiff). Not sure if this would incite a larger ram usage or not, but it would theoretically lead to smaller memory usage. It would be nice if @cloudiirain could provide some examples of how frequent the 'revert' tool will be used.

```js
{
  user_id: String,
  method: String, //GET/POST/DELETE etc
  url: String, // Like /api/v0.2/project
  hash: String  // in sha256
  object_id: String,
  object_diff: Object,
  timestamp
}
```

- When a new file is created with no prior object_id, object_diff consists of `new`.
- When an old file is updated with a prior object_id, a object_diff consists of `jsdiff(old,new)`
- When a patch is to be applied, jsdiff is recursively called until the object is returned to its original state

**Comment by cloudiirain** [comment]
Which we optimize for in some ways depends on the business model of the site. Baka-Tsuki reverts happen semi-frequently because anyone (even anonymous guests) can edit anything. If a spammer comes along, there we can expect a lot of reverting to happen. Additionally, it is common in Baka-Tsuki's culture for editors to edit-first, and translators to revert-later if they don't like the edits, since the translators and editors that work together don't really know each other.

I was more or less under the assumption that Hako's business model would differ in several ways:

- Unregistered guests can't make changes (no anonymous edits)
- Translators can define who has write access to their translations. They can either make the write-access public (like Baka-Tsuki), or they can restrict it to a small set of users/editors like an ordinary translation group (like Nanodesu).

So in short, maybe we'd have less reverting (we hope).

The only additional comment that I'll add is that AFAIK, Mediawiki stores the whole text with each revision (not the diff), and calculates the diff on the spot when the user wants to see the diff. In terms of database size, Baka-Tsuki is more-or-less manageable right now (it hasn't grown too gigantic yet). It's just text anyways, which isn't too bad... generally speaking the images take up more space on the server.

My opinion on this hinges in part on what we choose do for #2 

If Hako works similarly as Baka-Tsuki, I don't have any preference as towards whether we store diffs or store the full text. I think both are reasonable, though as you pointed out, one preferred over the other for reverting (and for previewing an old version without necessarily applying the revert).

If we implement a comment system that inserts place holders in the raw text, then I'd lean towards storing diffs because I think the history might inflate a bit more quickly if users comment a lot.

**Comment by cloudiirain** [comment]
Thinking about this model more, I actually don't think it's necessary to the URI, post data, and method. This would be a good strategy if we were creating a moderation queue (because we need to update the end-user with the response (success/failure) much later in the future). However, for the purposes of building a Revision History and Recent Changes, I think there are several advantages being explicit.

```
{
  user_id: String,
  action: String, //CREATE/UPDATE/DELETE etc
  model: String, // Like project/series/chapter
  object_id: String,
  hash: String  // in sha256, (what is this for? I just don't know, though I'm sure you have a really good reason XD)
  object_diff/payload: Object,
  timestamp: Date
}
```

On methods: Don't really need to store GET requests because we don't really need to be creating a log. If we track information this, this collection would inflate way too quickly and something will always be writing to it (which is bad for performance).

If we're not storing GET requests, and we're not returning any formatting response to the end-user in the future (the response has already been returned), isn't want we really mean here whether the stored action is a CREATE/UPDATE/DELETE?

On the url: You mentioned parsing for anything we need, though we can't index this. The essential information that we need from the url/post data is the model, the object_id, the data (or the diff). If we store the model name instead of the url, it will be faster to query on this (and we have an option of building an index on it).

For instance: To generate a full [revision history](https://www.baka-tsuki.org/project/index.php?title=Baka_to_Test_to_Shoukanjuu&action=history) on a particular series (using SQL to illustrate):

```
SELECT model, object_id, object_diff, timestamp
FROM model_history
WHERE model='project' AND object_id=7
ORDER BY timestamp;
```

Having the "where" on the model is necessary because I'm OCD about objects from different collections having the same _id. Shouldn't be a problem if we're using object_id's instead of integer id's, but I think it's better to be explicit since the database will ensure there are no collisions within the a single collection (but this doesn't extend to ensuring there isn't collisions in pk's across multiple collections).

If you use a diff method, you're going to want this query to be very reliable.

**Comment by Shadowys** [comment]
Yeah, GET is not required here, Only POST and DELETE are the ones needed.
Hash is for comparing diffs but then again if we might be storing diffs then there's no point for this lel.
user_id is for finding who to blame XD since only registered users can edit.
If we are storing diffs, we don't need the url except to parse the models. I'm still using the models here because I don't think mongo keeps track of the ObjectID from different models.
So the now the schema should look like this:
```js
{
  user_id: String,
  model: String, // Like project/series/chapter
  object_id: String,
  object_diff/payload: Object,
  timestamp: Date
}
```

**Comment by Shadowys** [comment]
Refer to #26 for the current implementation (pages in chapters and such)
