### ISSUE TITLE
Use numbers for keys

### ISSUE THREAD

**Issue by Shadowys** [Shadowys/hako#20]
It is possible to change MongoDB _id into a Integer type instead of ObjectID for a friendlier URI.

**Comment by cloudiirain** [comment]
I actually prefer _id as a semi-random String over an autoincrementing integer. 

Part of this is me being OCD... in that some databases (like postgresql), the autoincrementer has somewhat odd/unsafe behavior. For instance, postgresql will do this:

```
CREATE "first series" <--- receives an _id:1
CREATE "second series" <--- receives an _id:2
CREATE "third series" <--- receives an _id:3
DELETE Series with _id==2
CREATE "fourth series" <--- receives an _id:4 (this is good behavior)
CREATE "new series" <--- receives an _id:5
// Do lot of stuff with series (_id:5)
DELETE Series with _id==5
CREATE "another new series" <--- receives an _id:5 (again... which is bad behavior)
```

This is sort of problematic because the 6th series gets reassigned the id that used to belong to the deleted 5th series. 

It's not a serious problem for this database (if we take care of all the cascading deletes beforehand), but it's a problem for dependent apps that might have saved the URI for the old series with _id:5, or if we're doing some importing/exporting with fixtures.

I mean, I have no idea how mongo's integers would work, but I'm only saying this from my experience with postgreSQL. >____< There's a point where the random string id is safer.

**Comment by Shadowys** [comment]
I see. Yeah personally I would prefer using ObjectID for keys so I wouldn't have to worry about accessing old ids since mongo takes care of that for me, but you brought up a point users may save or bookmark a link, but the link has been deleted and they then have access to someone else's data. 

So I guess ObjectID it is.

**Comment by Shadowys** [comment]
Just for clarification, mongodb integer keys works the same as postgresql's AFAIK

**Comment by cloudiirain** [comment]
Well I mean, technically end-users aren't really bookmarking API links, so that actually isn't a huge problem. It's mostly the front-end app source code that is dealing with these API URI's.

The front-end app should have its own router and can choose to use title slugs or really anything it chooses.

**Comment by Shadowys** [comment]
Assuming that the front end dev wouldn't cache the id instead of using something saner XD Using ObjectIDs should discourage this behaviour.
