### ISSUE TITLE
Project and Series (Cost-benefit of Implementing?)

### ISSUE THREAD

**Issue by cloudiirain** [Shadowys/hako#25]
Was thinking about this topic today, especially since @Shadowys mentioned potentially merging our back-end data store with Nanodesu's.

If we ever consider doing this that many more times in the future, we should consider interoperability (the ease of exporting data in one system -- e.g. WuxiaWorld's database -- and plugging it into ours).

If interoperability is a focus, I think we may want to consider making our models as generic as possible. Mangaupdates, Myanimelist, lndb.info, and Novelupdates already have their own models, and for the most part, their database models are all the same.

I'm thinking that we can use the same models as the major players, since they have more-or-less have already set the standard for our subculture. It makes it easier to collaborate with the other major players (since each of those communities have their own admins/developers -- incidentally, I personally know the developer for Novelupdates).

For a large part, most of the major novel directories do not classify novels into projects (it's really on Baka-Tsuki that has done it in the past, and only in rare cases). They keep everything at the level of Series and have a field called "**related series**". 

Example: [Toaru Majutsu no Kinsho Mokuroku](https://www.mangaupdates.com/series.html?id=31840)

Each spin-off series gets its own page, and there is no way to view all the spin-offs in a single page. I think Novelupdates and Myanimelist do the same thing.

This behavior is reasonable, in my opinion, and makes the model simpler. Since we're working with Mongo, I think it's easier to model these sorts of relationships on a single field, rather having a whole new collection dedicated to Project (which is a parent of Series). 

It makes more sense for the front-end as well. For instance, with a Project parent collection, whenever a user wants to create a new Series, the front-end must create a new Project before creating a new Series (or at least accomplish this programmatically/automate it). 

With a "related series" as a field, a user that wants to create a new series can just make a new series without any complicated prerequisites (no upstream dependencies to fulfill). If they realize later on that series X is related to series Y (like a spin-off or sequel series), they can add the relationship afterwards. The relationship isn't required to be defined when a series is created (or can be NULL), which makes the User Experience a little bit easier/flexible when a Series is created. It's also more intuitive (at least, for me, I didn't understand at first what was the difference between a project and a series).

**Comment by Shadowys** [comment]
The original intent of the project-series separation of abstraction was to prevent data duplication. One major concern was that with the "related series", there is no main series to speak of, since each series is connected to each other. However, we are unable to guarantee that, from a backend perspective, all of each series will be linked together. The responsibility for maintaining that falls back to the user, and from BT's experience, that is very tedious to maintain, especially when the active manager goes MIA and the project gets larger. An example would be if you added a new series, and you link it to another, does all the other series update themselves? It becomes a O(n**n) mapping series to each series operation.

So while it would be simple conceptually, it would not be simple to maintain it in the long run. 

Projects aim to simplify that by placing all related series under an umbrella, so they all refer to the main project, so to speak. It is placed upon creation, and no other work is needed to maintain the series links. Projects, in a way, can be described as the "main series", which acts as the primary key for the series.

The main concern was that unlike other sites which do not have to maintain relationships between each series and could return the responsibility back to the end user to navigate through the pages, IMO a multi-series translation hub should make it easy for the manager to handle all different series at once without too much cognitive and technical load.

From a frontend perspective, automating the creation of a new series when a new project is created should be fairly easy to implement. 

I do agree that the concept Project-series is hard to get at first, but the front-end may be able to mitigate some of that confusion for new users.

**Comment by cloudiirain** [comment]
I'm just curious how all the major databases (mangaupdates, etc) have implemented the "related series". Surely they've worked through this problem, and it seems to be working well with them.

I agree that automating the creation of a project on the front-end is doable. However, we're more-or-less relegating this responsibility to the front-end developer (which isn't us, as back-end developers).

I think we have to keep in mind that the front-end developers are in a sense our "business clients" -- in that we want to make a system that is stable/comprehensive but sane/simple enough that most developers could get into development easily.

Another thing to keep in mind is that is there necessarily always a parent project?

For instance, Negima and UQ Holder. They're "related series", but is the parent project just the prequel? At a certain point, it becomes hard to distinguish which is the parent and which is the child.

**Comment by Shadowys** [comment]
Well, for the front end, I would think having it separated is easier to implement than having them map together because parsing through a one-to-many tree is much easier than parsing through a mapped many-to-many network which does not have validity guarantees.

For prequels I think they are handled as another series under the parent project, since they are related to each other, and they both map to the same identity.

**Comment by cloudiirain** [comment]
If we use the nullable franchise_id thing as suggested in #26, here's an idea on the UX end that may make it _seem_ like the user is selecting "related series" (even though the model is very different).

1. User is creating or editing a series
2. There is a select box called: "Choose a related series"
3. Selecting a series assigns that series's franchise_id to this one. Basically, we add this series into the set of series that already have the same franchise_id, and an AJAX update can display _all_ the series that would be related (with just one click!).
    1. If that series doesn't have a franchise id (it's null), then front-end needs to do some more gymnastics, automate creating a franchise, and assign both series to the franchise.

**Comment by Shadowys** [comment]
We probably need to move it into a front end requirement or feature though. Either choosing a franchise or picking a related series (probably in a form of a search box and suggested related series...there seems a lot of stuff that we can do with the data haha

**Comment by Shadowys** [comment]
#26
